### ISSUE TITLE
Error when using choo-devtools

### ISSUE THREAD

**Issue by btheado** [graforlock/choo-detached#1]
When I use choo-detached with choo-devtools, I'm getting an error: `wayfarer.getAllRoutes: router should be an function`.

Here is my test code:

```javascript
var choo = require('choo-detached')
var html = require('choo/html')

var app = choo()
app.use(require('choo-devtools')())
app.component(mainView)
app.mount('body')

function mainView (state, emit) {
  return html`
    <body>
      <p>hello, world</p>
    </body>
  `
}
```

I'm using choo 6.6.1, choo-detached 1.0.0, choo-devtools 2.3.0.

Is there something choo-detached can do to mock the router enough to satisfy choo-devtools?

**Comment by graforlock** [comment]
I don't think it would work, most of choo internals (thus tools as well) is tightly coupled with the router idea.

**Comment by graforlock** [comment]
Im just going to have a look and give it a try nonetheless.

**Comment by btheado** [comment]
Thanks. I just got back around to this and I found with the new choo 6.7.0, a router error happens even without choo-devtools. But the new code in 6.7.0 makes it easier to override the route functionality. Have a look at my pull request and let me know what you think.

I also just found https://github.com/heyitsmeuralex/nanochoo which gives similar functionality to choo-detached, It takes the approach of forking choo directly and removing the router piece. Maybe that one will be harder to maintain and will be more likely to fall behind choo-detached? Both it and nanochoo have a  fairly small amount of code, so either way it might not matter much.

**Comment by graforlock** [comment]
Yeah, so it seems its a good idea to do that.

And I agree that maybe `nanochoo` seems to be taking the heavyweight approach where they change `choo` API whereas `choo-detached` aims to make a tiny extension with leaving the API intact.
